Hero section for mobile version
NickEmma/techie-emma-portfolio pull request #1
Opened 2022-05-25 22:20 UTC by NickEmma

2022-05-25 23:18 UTC, smunozmo requested changes
Hi @NickEmma, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no Pull Request description and is not running the linters checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-25 23:24 UTC, Ginohmk reviewed
Hi @NickEmma , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-25 23:24 UTC, Ginohmk commented on .stylelintrc.json
> +}
- This code will be marked as invalid, please set up your linters correctly by running the commands [here]()

2022-05-26 08:23 UTC, NickEmma commented on .stylelintrc.json
> +}
Thanks it was helpful and I have resolved the issue and fixed the error

2022-05-26 09:22 UTC, Rustamxon7 requested changes
Hi @NickEmma , 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯
- Descriptive Readme.md. 💯


There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 09:22 UTC, Rustamxon7 commented on styles.css
> +  text-transform: capitalize;
- [ ] Please remove this line because not all of the text should be capitalized 👍🏼

2022-05-26 09:22 UTC, Rustamxon7 commented on styles.css
> +}
- [ ] Please change the color of the black part in the h1 text and paragraph in the hero section to `#172B4D` (you can use your --dark-blue variable) 🙌🏼

## Your design
![image](https://user-images.githubusercontent.com/69011963/170457973-b9cd1e00-13c0-4147-a27c-53b7f0807836.png)



## Original design
![image](https://user-images.githubusercontent.com/69011963/170457885-e7272ba6-7ee1-4e68-9661-6aed0d86670b.png)

2022-05-26 09:22 UTC, Rustamxon7 commented on index.html
> +      </div>
- [ ] Please also change `social-icon` `div` to `ul` tag and add `li` elements for each icons 👌🍀

2022-05-26 09:22 UTC, Rustamxon7 commented on README.md
> +This project [MIT](./MIT.md) licensed.
- [ ] [OPTIONAL] Let's also add the MIT license file 👋📃

2022-05-26 09:23 UTC, Rustamxon7 commented on README.md
> +This project [MIT](./MIT.md) licensed.
- [ ] Pull request should have a description text. I would recommend adding list of thing that you adding in this repo

2022-05-26 09:43 UTC, NickEmma commented on styles.css
> +  text-transform: capitalize;
Fix the text transform

2022-05-26 09:53 UTC, NickEmma commented on index.html
> +      </div>
Made changes to the social icon to use a ul tag

2022-05-26 09:54 UTC, NickEmma commented on README.md
> +This project [MIT](./MIT.md) licensed.
okay it is fixed

2022-05-26 11:09 UTC, danielufeli approved these changes
Hi @NickEmma ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Design✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 11:13 UTC, merged