A Work section and About Me
NickEmma/techie-emma-portfolio pull request #2
Opened 2022-05-26 17:25 UTC by NickEmma

## This is how i designed this section
- Added a work section to show my works
-  Added an about me to tell clients what I do
- Added a hover effect to change the color when a mouse is placed on it
- Displayed all the skills I have

2022-05-26 18:17 UTC, youmari requested changes
Hi @NickEmma , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [x] doesn't have all linters green please make sure all the linter are green

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 19:16 UTC, Ismailco requested changes
### Hi @NickEmma,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️

- Please fix the ```MIT LICENSE ``` link on the  README file, it's messing
- Please add Acknowledgments on the README or remove this part from your README file ``` from line 42 to line 46```

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 19:16 UTC, Ismailco commented on index.html
> +        <h1 class="heading">My Recent Works</h1>
- [ ] You should always use only one ```<h1>``` tag on your page, this is good for SEO and respects the best practices. please consider using another ```hx``` tag, you could use ```<h2>``` here so the ```hx``` hierarchy is respected

2022-05-26 19:16 UTC, Ismailco commented on styles.css
> +
- [ ] [Optional] This is not required but it would be great if the page takes all the horizontal space available, you can do this by using ```vh```/```vw``` for sizes instead of ```px```

![Screenshot_20220526_201151](https://user-images.githubusercontent.com/25227022/170560428-5356e759-d581-4e5d-b4d1-b720cc5bc90f.png)

2022-05-26 21:27 UTC, NickEmma commented on index.html
> +        <h1 class="heading">My Recent Works</h1>
Thanks for the hint

2022-05-26 21:35 UTC, NickEmma commented
I'M reaching out to let you know that the review is not clear enough. the
part you are pointing at is different from the code

On Thu, 26 May 2022 at 20:16, ismail courr ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hi @NickEmma <https://github.com/NickEmma>,
>
> Good job so far 👍🏼
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✔️ No linter errors
> ✔️ Used Github Flow
> ✔️ Work documented professionally
> Required Changes ♻️
>
>    - Please fix the MIT LICENSE link on the README file, it's messing
>    - Please add Acknowledgments on the README or remove this part from
>    your README file from line 42 to line 46
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#discussion_r882986931>
> :
>
> > @@ -54,5 +57,279 @@ <h1>Hey there. I’m Nicholas <span> I’m a software developer</span></h1>
>
>          </a>
>
>        </div>
>
>      </section>
>
> +
>
> +    <!-- ========== works section starts ==========  -->
>
> +
>
> +    <section class="works">
>
> +      <div class="indicator">
>
> +        <h1 class="heading">My Recent Works</h1>
>
>
>
>    - You should always use only one <h1> tag on your page, this is good
>    for SEO and respects the best practices. please consider using another
>    hx tag, you could use <h2> here so the hx hierarchy is respected
>
> ------------------------------
>
> In styles.css
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#discussion_r882992859>
> :
>
> >    display: flex;
>
>    text-align: center;
>
>    align-items: center;
>
>    justify-content: center;
>
>    flex-wrap: wrap;
>
>  }
>
> +
>
>
>
>    - [Optional] This is not required but it would be great if the page
>    takes all the horizontal space available, you can do this by using vh/
>    vw for sizes instead of px
>
> [image: Screenshot_20220526_201151]
> <https://user-images.githubusercontent.com/25227022/170560428-5356e759-d581-4e5d-b4d1-b720cc5bc90f.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#pullrequestreview-986667357>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRL5ERTSRSMPHTWZQOLVL7E2FANCNFSM5XB2H7TQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-26 21:51 UTC, NickEmma commented on styles.css
> +
The review is not clear enough, I am finding it difficult to understand
because you were pointing at another place and displaying an image of my work and I'm work with the width indicated to us on figma

2022-05-26 22:31 UTC, mukhammadrizooff requested changes
Hi @NickEmma , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- All linters passed 💯 
- Correct use of Gitflow 💯 
- Descriptive messages 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 22:31 UTC, mukhammadrizooff commented on index.html
> +        <img src="./images/Indicator.png" alt="" />
- [ ] Please make changes! The title should (e.g., "My Recent Works") uses a header tag `hx`.

2022-05-26 22:31 UTC, mukhammadrizooff commented on index.html
> +            </h3>
- [ ] [REQUIRED] Good job so far! Please all project titles should (e.g., "Tonic") use a header tag `hx`.

2022-05-26 22:31 UTC, mukhammadrizooff commented on index.html
> +        <p>
- [ ] Please make changes! The title should (e.g., "About myself") uses a header tag `hx`

2022-05-26 22:31 UTC, mukhammadrizooff commented on styles.css
>  }
- [ ] [OPTIONAL] You have done the work required by the previous inspector very well! The section has the margins (top, bottom, left, right) defined in the design 👍

2022-05-26 22:34 UTC, Ismailco commented on styles.css
> +
@NickEmma, I am talking about the whole page, you can see the white space on the right. it will be better if you removed it by expanding the elements on the page including the project cards to the right, one way you can do that is by giving a width of 100vw to the sections on your page

2022-05-26 23:21 UTC, NickEmma commented on index.html
> +        <img src="./images/Indicator.png" alt="" />
My work already uses the hx tag, please put it clear for me to understand

2022-05-26 23:22 UTC, NickEmma commented on index.html
> +            </h3>
I have those, i made use of hx

2022-05-26 23:23 UTC, NickEmma commented on index.html
> +        <p>
i don't understand

2022-05-26 23:23 UTC, NickEmma commented on styles.css
>  }
yes it's optional

2022-05-26 23:25 UTC, NickEmma commented
i mad use of hx tags so it's not clear, like i don't understand

On Thu, 26 May 2022 at 23:34, ismail courr ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In styles.css
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#discussion_r883131342>
> :
>
> >    display: flex;
>    text-align: center;
>    align-items: center;
>    justify-content: center;
>    flex-wrap: wrap;
>  }
> +
>
> @NickEmma <https://github.com/NickEmma>, I am talking about the whole
> page, you can see the white space on the right. it will be better if you
> removed it by expanding the elements on the page including the project
> cards to the right, one way you can do that is by giving a width of 100vw
> to the sections on your page
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#discussion_r883131342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRKB55J6WXZLBYXZBL3VL74AFANCNFSM5XB2H7TQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-27 00:10 UTC, mukhammadrizooff commented
### @NickEmma I apologize for the PR let that the issue will be resolved after a few hours.

2022-05-27 05:49 UTC, NickEmma commented
Thanks you for your response, I'll be waiting for it to be resolve.

On Fri, May 27, 2022, 1:11 AM Muhammad Rizo ***@***.***>
wrote:

> @NickEmma <https://github.com/NickEmma> I apologize for the PR let that
> the issue will be resolved after a few hours.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/techie-emma-portfolio/pull/2#issuecomment-1139164667>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRROT7BGEFEWEI5362D3VMAHKNANCNFSM5XB2H7TQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-27 10:15 UTC, sinansevgi reviewed
Hello @NickEmma  👋,

_This is an additional review as a result of the second opinion request._

The requested changes about the header tags are part of the project requirement but should have been **optional** because it was not pointed out by the first reviewer. Since you already made the changes and requested changes should have been optional in the first place, I think your project should get approved. 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it **manually** so this could take a few hours!

Keep rocking 🚀!

2022-05-31 09:55 UTC, merged